### ISSUE TITLE
有的俗语解释字段前有方括号

### ISSUE THREAD

**Issue by Guanchishan** [MindongLab/foochow-idioms-data#1]
福州话熟语大全的数据中，如图：
![image](https://user-images.githubusercontent.com/30859354/74382224-45b06f00-4ded-11ea-90e2-8e79d7273726.png)
不知为何，也不知应如何解决。
@ztl8702

**Comment by ztl8702** [comment]
删掉？

另， 
 这个 [csv](https://github.com/MindongLab/foochow-idioms-data/blob/master/%E7%A6%8F%E5%B7%9E%E6%96%B9%E8%A8%80%E7%86%9F%E8%AF%AD%E6%AD%8C%E8%B0%A3.csv)。这个和榕典不一样，即更新这边并不会更新 idioms.mindong.asia。
 idioms.mindong.asia实际内容在一个数据库中，和这个csv不同步。我怀疑它的内容已经和这个csv有偏离了。 （有时间可以考虑把idioms.mindong.asia也改用榕典模式，即使用 git 中的文件作为 source of truth）

**Comment by Guanchishan** [comment]
> 有时间可以考虑把idioms.mindong.asia也改用榕典模式，即使用 git 中的文件作为 source of truth

那听起来不错。那这个方括号问题就不予理会了。
