### ISSUE TITLE
[福州熟语歌谣] 做鬼也me抢冥头斋 (OCR錯誤)

### ISSUE THREAD

**Issue by ztl8702** [MindongLab/foochow-idioms-data#77]
http://idioms.mindong.asia/#/idiom/%E5%81%9A%E9%AC%BC%E4%B9%9F%F0%A3%8D%90%E6%8A%A2%E5%86%A5%E5%A4%B4%E6%96%8B%E3%80%82

`无能之萆，到死还是无能的。` 疑ocr错误，待改。

**Comment by Guanchishan** [comment]
done
